export const CATEGORIES = [
  'Online Courses and Workshops',
  'Ebooks and Audiobooks',
  'Workbooks and Guides',
  'Paid Newsletters',
  'Digital Planners and Journals',
  'Software and Plugins',
  'Notion and Spreadsheet Templates',
  'Swipe Files and Cheat Sheets',
  'Graphic Design Elements',
  'Fonts',
  '3D Models',
  'Stock Photography',
  'Presets and LUTs',
  'Music and Sound Effects',
  'Video Footage and Animations',
  'AI Prompts',
  'Memberships and Communities',
  'Ebook',
  'Course',
  'Template',
  'Audio',
  'Software',
]
